version: '3.8'
services:
  sql-server2019:
    image: 'mcr.microsoft.com/azure-sql-edge'
    environment:
      SA_PASSWORD: 'root@123'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    networks: 
      - vity01
    restart:
      always
    volumes:
      - './data:/var/opt/mssql'

networks:
  vity01:
